[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "sales-insight"
version = "0.1.0"
description = "Análise e visualização de dados de vendas com Python"
requires-python = ">=3.12,<3.14"

dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "ipython"
]

[tool.setuptools.packages.find]
where = ["src"]