DICIONARIO_DADOS = {
    "Coluna": [
        "id_venda",
        "data_venda",
        "id_cliente",
        "nome_cliente",
        "cidade",
        "estado",
        "regiao",
        "id_produto",
        "produto",
        "categoria",
        "quantidade",
        "preco_unitario",
        "desconto",
        "previsao_entrega",
        "data_entrega",
    ],
    "Descrição": [
        "Identificador único da venda.",
        "Data em que a venda foi realizada.",
        "Identificador do cliente associado à venda.",
        "Nome do cliente.",
        "Cidade de residência do cliente.",
        "Estado de residência do cliente.",
        "Região geográfica associada ao cliente.",
        "Identificador do produto vendido.",
        "Nome do produto vendido.",
        "Categoria à qual o produto pertence.",
        "Quantidade de unidades vendidas na transação.",
        "Preço unitário do produto no momento da venda.",
        "Desconto aplicado à transação, formato decimal.",
        "Data prevista para a entrega do pedido.",
        "Data em que o pedido foi efetivamente entregue.",
    ],
}
